
Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mmeta-pipeline[0m and container [32mstep-credential-initializer-hlzft[0m
{"level":"warn","ts":1568806040.1034467,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1568806040.1043963,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mmeta-pipeline[0m and container [32mstep-working-dir-initializer-sn7z4[0m
{"level":"warn","ts":1568806043.1426446,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1568806043.1465764,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"mkdir -p /workspace/source\""}

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mmeta-pipeline[0m and container [32mstep-place-tools[0m

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mmeta-pipeline[0m and container [32mstep-git-source-meta-khoatdd-jenkinx-python-mas-7dfwj[0m
{"level":"warn","ts":1568806059.1082969,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1568806062.504682,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/*******/jenkinx-python.git @ 199c9cf68327326e99cda76a40f664604e560bc8 in path /workspace/source"}

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mmeta-pipeline[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:199c9cf68327326e99cda76a40f664604e560bc8
WARNING: no SHAs to merge, falling back to initial cloned commit

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mmeta-pipeline[0m and container [32mstep-merge-pull-refs[0m
SKIP merge-pull-refs: Nothing to merge

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mmeta-pipeline[0m and container [32mstep-create-effective-pipeline[0m
Deleting and cloning the Jenkins X versions repo
Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with ref refs/heads/master to /builder/home/.**/jenkins-x-versions
Effective pipeline written to jenkins-x-effective.yml

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mmeta-pipeline[0m and container [32mstep-create-tekton-crds[0m
running command: echo \$(**-release-version) > VERSION

running command: ** step tag --version \$(cat VERSION)
Updating chart version in charts/jenkinx-python/Chart.yaml to 0.0.1
Updating repository in charts/jenkinx-python/values.yaml to 263714803598.dkr.ecr.ap-southeast-1.amazonaws.com/*******/jenkinx-python
Updating tag in charts/jenkinx-python/values.yaml to 0.0.1
Tag v0.0.1 created and pushed to remote origin

WARNING: failed to find secret kaniko-secret in namespace **: secrets "kaniko-secret" not found
PipelineActivity for *******-jenkinx-python-master-1
Applying changes 
upserted PipelineResource *******-jenkinx-python-master for the git repository https://github.com/*******/jenkinx-python.git
upserted Task *******-jenkinx-python-master-from-build-pack-1
upserted Pipeline *******-jenkinx-python-master-1
created PipelineRun *******-jenkinx-python-master-1
created PipelineStructure *******-jenkinx-python-master-1

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-mwtg6[0m
{"level":"warn","ts":1568806084.8183792,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1568806084.8188372,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-ll4vt[0m
{"level":"warn","ts":1568806088.2311885,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1568806088.2321193,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"mkdir -p /workspace/source /workspace/source/charts/jenkinx-python\""}

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-khoatdd-jenkinx-python-master-2flrn[0m
{"level":"warn","ts":1568806111.3479443,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1568806114.4363198,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/*******/jenkinx-python.git @ v0.0.1 in path /workspace/source"}

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:199c9cf68327326e99cda76a40f664604e560bc8
WARNING: no SHAs to merge, falling back to initial cloned commit

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-jx-git-credentials[0m
Generated Git credentials file /workspace/xdg_config/git/credentials

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:onbuild        
[36mINFO[0m[0002] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0002] Downloading base image python:onbuild        
[36mINFO[0m[0004] Executing 3 build triggers                   
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] Checking for cached layer 263714803598.dkr.ecr.ap-southeast-1.amazonaws.com/todo/cache:f96ea06eb1dc1e896fb6ba60e374488f43e9918d4fe1cb30c5f26c8dea340a73... 
[36mINFO[0m[0004] No cached layer found for cmd RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0004] Unpacking rootfs as cmd RUN pip install --no-cache-dir -r requirements.txt requires it. 
[36mINFO[0m[0020] Taking snapshot of full filesystem...        
[36mINFO[0m[0025] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0025] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0025] Taking snapshot of files...                  
[36mINFO[0m[0025] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0025] cmd: /bin/sh                                 
[36mINFO[0m[0025] args: [-c pip install --no-cache-dir -r requirements.txt] 
You are using pip version 10.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[36mINFO[0m[0026] Taking snapshot of full filesystem...        
[36mINFO[0m[0029] Using files from context: [/workspace/source] 
[36mINFO[0m[0029] Pushing layer 263714803598.dkr.ecr.ap-southeast-1.amazonaws.com/todo/cache:f96ea06eb1dc1e896fb6ba60e374488f43e9918d4fe1cb30c5f26c8dea340a73 to cache now 
[36mINFO[0m[0029] COPY . /usr/src/app                          
[36mINFO[0m[0029] Taking snapshot of files...                  
[36mINFO[0m[0029] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0029] COPY requirements.txt .                      
[36mINFO[0m[0029] Taking snapshot of files...                  
[36mINFO[0m[0029] ENV PORT 8080                                
[36mINFO[0m[0029] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0029] EXPOSE 8080                                  
[36mINFO[0m[0029] cmd: EXPOSE                                  
[36mINFO[0m[0029] Adding exposed port: 8080/tcp                
[36mINFO[0m[0029] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0029] ENTRYPOINT ["python"]                        
[36mINFO[0m[0029] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0029] CMD ["app.py"]                               
[36mINFO[0m[0029] No files changed in this command, skipping snapshotting. 
[33mWARN[0m[0029] error uploading layer to cache: failed to push to destination 263714803598.dkr.ecr.ap-southeast-1.amazonaws.com/todo/cache:f96ea06eb1dc1e896fb6ba60e374488f43e9918d4fe1cb30c5f26c8dea340a73: NAME_UNKNOWN: The repository with name 'todo/cache' does not exist in the registry with id '263714803598' 
2019/09/18 11:29:06 pushed blob: sha256:d7d92fa495d7056e5c313e95ed1a99282fe90d6c73c98e6e66a7808d8e392485
2019/09/18 11:29:06 pushed blob: sha256:e1cd19d65a0843026ba0dcd9da10eb11800e6ffbb42c99364ff39ce79b80aff3
2019/09/18 11:29:06 pushed blob: sha256:3f9fb36909de41f948f7e2a177a90530d6e40ce85f6ebe6fa217d725cb5989f9
2019/09/18 11:29:06 pushed blob: sha256:c7d0196adcfb02f643310222a3f2b295813df53c775fc877ab4f166b76f8a463
2019/09/18 11:29:07 pushed blob: sha256:aa66284aab59dd7d9cdadd3b322169d24a001e341f76f59fd635074dab432967
2019/09/18 11:29:07 pushed blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2019/09/18 11:29:07 pushed blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2019/09/18 11:29:07 pushed blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2019/09/18 11:29:08 pushed blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2019/09/18 11:29:09 pushed blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2019/09/18 11:29:10 pushed blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2019/09/18 11:29:13 pushed blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2019/09/18 11:29:14 pushed blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2019/09/18 11:29:24 pushed blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2019/09/18 11:29:24 263714803598.dkr.ecr.ap-southeast-1.amazonaws.com/*******/jenkinx-python:0.0.1: digest: sha256:688a3ab8c0c669aac190257b53213b7df7819a829c13af320945f78b7d3be676 size: 2385

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-changelog[0m
Converted /workspace/source/charts/jenkinx-python to an unshallow repository
no previous commit version found so change diff unavailable

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-helm-release[0m
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Uploading chart file jenkinx-python-0.0.1.tgz to http://jenkins-x-chartmuseum:8080/api/charts
Received 201 response: {"saved":true}

Showing logs for build [32mkhoatdd-jenkinx-python-master-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-promote[0m
WARNING: prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/**/issues/2410
Promoting app jenkinx-python version 0.0.1 to namespace **-staging
Created Pull Request: https://github.com/*******/environment-sentrysharp-staging/pull/1
WARNING: Failed to query the Pull Request last commit status for https://github.com/*******/environment-sentrysharp-staging/pull/1 ref 4c7c5f0b28b6527b0ef9e9b44bb5271baae77c45 Could not find a status for repository *******/environment-sentrysharp-staging with ref 4c7c5f0b28b6527b0ef9e9b44bb5271baae77c45
WARNING: Failed to query the Pull Request last commit status for https://github.com/*******/environment-sentrysharp-staging/pull/1 ref 4c7c5f0b28b6527b0ef9e9b44bb5271baae77c45 Could not find a status for repository *******/environment-sentrysharp-staging with ref 4c7c5f0b28b6527b0ef9e9b44bb5271baae77c45
Pull Request https://github.com/*******/environment-sentrysharp-staging/pull/1 is merged at sha 1499d458f2558c2899e0293877480bc5d4418a2b
Pull Request merged but we are not waiting for the update pipeline to complete!
WARNING: Could not find the service URL in namespace **-staging for names jenkinx-python, **-jenkinx-python, **-staging-jenkinx-python
